version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/local_db2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - JWT_SECRET=your-very-secure-secret-key
      - JWT_EXPIRATION=3600000
    depends_on:
      - postgres
  postgres:
    container_name: localPostgresSQLDB2
    image: postgres
    environment:
      - POSTGRES_DB=local_db2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5332:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: